kind = "api"
previewPath = "/"
title = "GroundTube"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 8082
name = "GroundTube"
paths = ["/"]

[services.env]
PORT = "8082"

[services.development]
run = "cd /home/runner/workspace/artifacts/groundtube && python3 app.py"

[services.production]

[services.production.run]
args = ["sh", "-c", "cd /home/runner/workspace/artifacts/groundtube && python3 app.py"]

[services.production.run.env]
PORT = "8080"
